version: '2'
services:
  evklid:
    build: .
    volumes:
      - .:/usr/discrete-eltech
    ports:
      - '8888:8888'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.2
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
