version: '2'
services:
  evklid:
    build: .
    volumes:
    - .:/usr/discrete-eltech
    ports:
    - '80:80'
  mongo:
    container_name: mongo
    image: mongo:3.2
    ports:
    - "27017:27017"
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - '9000:9000'
volumes:
  portainer_data:
