version: '2'
services:
  evklid:
    build: .
    ports:
      - '8888:8888'
    environment:
      - DATABASE=user:secret@host:27017/database_name
      - GOOGLE_CLIENT_SECRET=""
      - GOOGLE_CLIENT_ID=""
      - GOOGLE_CALBACK_URL=""
      - GOOGLE_CALBACK_URL_LOGIN=""
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.2
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
